### PR TITLE
ECR Image Fix

### LINKED ISSUE #123: Unable to add ECR image to the allowlist through the execution log
Hello and thank you for working on these cleanup scripts.

My issue is that when I try to whitelist ecr resources through the execution log, it whitelists the repository but is unable to whitelist any image. When trying to whitelist an image I get the following errors:
- execution log error: `Resource ID `ecr:image:sha256:12abcded5sdsd5s4desdtgsdsdsd7shds7ds7dsjds7djsd7sdjs7dsdabcdefgh` is invalid`
- cloudwatch error: `[ERROR] too many values to unpack (expected 3)` 

I have tested on 2 accounts but get the same invalid resource ID error messages.

Thank you.

### PR DESCRIPTION
**Pull request by mlevit**
## Description

- Fixed issue with not being able to allowlist ECR Images.
- Fixed issue with ECR Image cleanup never being run.

### Related issue(s) (if applicable)

- Fixes #123

### CODE REVIEW

File: web/src/js/index.js [hunk 1]
```diff
@@ -374,12 +374,18 @@ function getAllowlist() {
       dayjs.extend(dayjs_plugin_timezone);
 
       app.allowlist = allowlistRaw.map((item) => {
+        // Parse Resource ID, i.e. split on ":"
+        let parsedResourceId = item["resource_id"].split(":", 2);
+        parsedResourceId.push(
+          item["resource_id"].slice(parsedResourceId.join("").length + 2)
+        );
```
Comment (mlevit) [inline web/src/js/index.js:381]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        );
```

Comment (mlevit) [inline web/src/js/index.js:381]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        );
```

Comment (mlevit) [inline web/src/js/index.js:381]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        );
```

File: web/src/js/index.js [hunk 2]
```diff
@@ -1,473 +1,479 @@
...
+// Get the API Gateway Base URL from manifest file
+fetch("serverless.manifest.json").then(function (response) {
+  response.json().then(function (data) {
+    let env = Object.keys(data)[0];
+    let API_BASE = data[env]["urls"]["apiGatewayBaseURL"];
+
+    API_GET_ALLOWLIST = API_BASE + API_GET_ALLOWLIST;
+    API_SERVICES = API_BASE + API_SERVICES;
+    API_CRUD_ALLOWLIST = API_BASE + API_CRUD_ALLOWLIST;
+    API_EXECLOG = API_BASE + API_EXECLOG;
```
Comment (mlevit) [inline web/src/js/index.js:466]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
    API_EXECLOG = API_BASE + API_EXECLOG;
```

File: web/src/js/index.js [hunk 3]
```diff
@@ -1,473 +1,479 @@
...
+    createAllowlistEntryFromExecutionLog: function (
+      service,
+      resource,
+      resourceId
+    ) {
+      this.selectedService = service.toLowerCase().replace(/ /g, "_");
+      this.selectedResource = resource.toLowerCase().replace(/ /g, "_");
+      this.selectedResourceId = resourceId;
+      this.updateResourceList(this.selectedService);
+      this.closeExecutionLogPopup();
```
Comment (mlevit) [inline web/src/js/index.js:95]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
      this.closeExecutionLogPopup();
```

File: web/src/js/index.js [hunk 4]
```diff
@@ -1,473 +1,479 @@
...
+        owner: this.selectedOwner,
+        comment: this.selectedComment,
+      };
+
+      sendApiRequest(convertJsonToGet(formData), "POST");
+    },
+    createAllowlistEntryFromExecutionLog: function (
+      service,
+      resource,
+      resourceId
```
Comment (mlevit) [inline web/src/js/index.js:89]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
      resourceId
```

File: web/src/js/index.js [hunk 5]
```diff
@@ -1,473 +1,479 @@
...
+      this.selectedOwner = "";
+      this.selectedResource = "";
+      this.selectedResourceId = "";
+      this.selectedService = "";
+      this.showAllowlistPopup = false;
+    },
+    createAllowlistEntry: function () {
+      let formData = {
+        resource_id:
+          this.selectedService +
```
Comment (mlevit) [inline web/src/js/index.js:75]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
          this.selectedService +
```

File: web/src/js/index.js [hunk 6]
```diff
@@ -1,473 +1,479 @@
...
+      this.executionLogRegionStats = {};
+      this.executionLogServiceStats = {};
+      this.showExecutionLogPopup = false;
+    },
+    openExecutionLog: function (keyURL) {
+      $("html").addClass("remove-overflow");
+
+      getExecutionLog(keyURL);
+    },
+    searchExecutionLog: function () {
```
Comment (mlevit) [inline web/src/js/index.js:159]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
    searchExecutionLog: function () {
```

File: web/src/js/index.js [hunk 7]
```diff
@@ -1,473 +1,479 @@
...
+    createAllowlistEntry: function () {
+      let formData = {
+        resource_id:
+          this.selectedService +
+          ":" +
+          this.selectedResource +
+          ":" +
+          this.selectedResourceId,
+        owner: this.selectedOwner,
+        comment: this.selectedComment,
```
Comment (mlevit) [inline web/src/js/index.js:81]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        comment: this.selectedComment,
```

File: web/src/js/index.js [hunk 8]
```diff
@@ -1,473 +1,479 @@
...
+
+    API_GET_ALLOWLIST = API_BASE + API_GET_ALLOWLIST;
+    API_SERVICES = API_BASE + API_SERVICES;
+    API_CRUD_ALLOWLIST = API_BASE + API_CRUD_ALLOWLIST;
+    API_EXECLOG = API_BASE + API_EXECLOG;
+
+    for (output of data[env]["outputs"]) {
+      if (output["OutputKey"] === "AccountID") {
+        app.accountId = output["OutputValue"];
+        document.title = "AWS Auto Cleanup - " + output["OutputValue"];
```
Comment (mlevit) [inline web/src/js/index.js:471]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        document.title = "AWS Auto Cleanup - " + output["OutputValue"];
```

File: web/src/js/index.js [hunk 9]
```diff
@@ -1,473 +1,479 @@
...
+      let formData = {
+        resource_id: row.resource_id,
+        expiration: row.expiration,
+        owner: row.owner,
+        comment: row.comment,
+      };
+
+      sendApiRequest(convertJsonToGet(formData), "PUT");
+    },
+    updateResourceId: function (service, resource) {
```
Comment (mlevit) [inline web/src/js/index.js:116]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
    updateResourceId: function (service, resource) {
```

File: web/src/js/index.js [hunk 10]
```diff
@@ -1,473 +1,479 @@
...
+      app.closeAllowlistInsertPopup();
+      app.closeAllowlistDeletePopup();
+
+      iziToast.success({
+        color: "#3FBF61",
+        message: data.message,
+        messageColor: "white",
+      });
+    })
+    .catch((error) => {
```
Comment (mlevit) [inline web/src/js/index.js:212]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
    .catch((error) => {
```

File: web/src/js/index.js [hunk 11]
```diff
@@ -1,473 +1,479 @@
...
+        );
+
+        let readableDate = dayjs.unix(item["expiration"]).tz(dayjs.tz.guess());
+
+        item["row_id"] = i++;
+        item["service"] = parsedResourceId[0];
+        item["resource"] = parsedResourceId[1];
+        item["id"] = parsedResourceId[2];
+
+        item["expiration_readable"] = readableDate.format(
```
Comment (mlevit) [inline web/src/js/index.js:390]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        item["expiration_readable"] = readableDate.format(
```

File: web/src/js/index.js [hunk 12]
```diff
@@ -1,473 +1,479 @@
...
+
+      this.executionLogActionStats = {};
+      this.executionLogRegionStats = {};
+      this.executionLogServiceStats = {};
+      this.showExecutionLogPopup = false;
+    },
+    openExecutionLog: function (keyURL) {
+      $("html").addClass("remove-overflow");
+
+      getExecutionLog(keyURL);
```
Comment (mlevit) [inline web/src/js/index.js:157]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
      getExecutionLog(keyURL);
```

File: web/src/js/index.js [hunk 13]
```diff
@@ -1,473 +1,479 @@
...
+      this.showAllowlistPopup = false;
+    },
+    createAllowlistEntry: function () {
+      let formData = {
+        resource_id:
+          this.selectedService +
+          ":" +
+          this.selectedResource +
+          ":" +
+          this.selectedResourceId,
```
Comment (mlevit) [inline web/src/js/index.js:79]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
          this.selectedResourceId,
```

File: web/src/js/index.js [hunk 14]
```diff
@@ -1,473 +1,479 @@
...
+      "x-api-key": API_KEY,
+    },
+  })
+    .then((response) => response.json())
+    .then((data) => {
+      app.executionLogTable = data["response"]["body"];
+      app.executionLogKey = decodeURIComponent(executionLogUrl);
+
+      setTimeout(function () {
+        app.executionLogDataTables = $("#execution-log-table").DataTable({
```
Comment (mlevit) [inline web/src/js/index.js:238]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        app.executionLogDataTables = $("#execution-log-table").DataTable({
```

File: web/src/js/index.js [hunk 15]
```diff
@@ -1,473 +1,479 @@
...
+        let logDate = new Date(row["date"] + " UTC");
+        let localDate = logDate.toString().split(/ GMT/)[0];
+
+        row["key_escape"] = encodeURIComponent(row["key"]);
+        row["local_date"] = localDate;
+        return row;
+      });
+      setTimeout(function () {
+        $("#execution-log-list-table").DataTable({
+          dom: "rtp",
```
Comment (mlevit) [inline web/src/js/index.js:302]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
          dom: "rtp",
```

File: web/src/js/index.js [hunk 16]
```diff
@@ -1,473 +1,479 @@
...
+    updateResourceId: function (service, resource) {
+      this.resourceIdPlaceholder =
+        this.serviceSettings[service][resource]["id"];
+    },
+    updateResourceList: function (service) {
+      this.resourceList = Object.keys(this.serviceSettings[service]);
+
+      // auto select if only 1 option exists
+      if (this.resourceList.length === 1) {
+        this.selectedResource = this.resourceList[0];
```
Comment (mlevit) [inline web/src/js/index.js:125]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        this.selectedResource = this.resourceList[0];
```

File: web/src/js/index.js [hunk 17]
```diff
@@ -1,473 +1,479 @@
...
+      });
+    });
+}
+
+// Get execution log for a single instance
+function getExecutionLog(executionLogUrl) {
+  app.showExecutionLogPopup = true;
+  app.showExecutionLogLoadingGif = true;
+
+  fetch(API_EXECLOG + executionLogUrl, {
```
Comment (mlevit) [inline web/src/js/index.js:227]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
  fetch(API_EXECLOG + executionLogUrl, {
```

File: web/src/js/index.js [hunk 18]
```diff
@@ -1,473 +1,479 @@
...
+          ":" +
+          this.selectedResourceId,
+        owner: this.selectedOwner,
+        comment: this.selectedComment,
+      };
+
+      sendApiRequest(convertJsonToGet(formData), "POST");
+    },
+    createAllowlistEntryFromExecutionLog: function (
+      service,
```
Comment (mlevit) [inline web/src/js/index.js:87]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
      service,
```

File: web/src/js/index.js [hunk 19]
```diff
@@ -1,473 +1,479 @@
...
+function init() {
+  getAllowlist();
+  getExecutionLogList();
+  getServices();
+}
+
+// Get the API Gateway Base URL from manifest file
+fetch("serverless.manifest.json").then(function (response) {
+  response.json().then(function (data) {
+    let env = Object.keys(data)[0];
```
Comment (mlevit) [inline web/src/js/index.js:460]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
    let env = Object.keys(data)[0];
```

File: web/src/js/index.js [hunk 20]
```diff
@@ -1,473 +1,479 @@
...
+  })
+    .then((response) => response.json())
+    .then((data) => {
+      refreshAllowlist();
+      app.closeAllowlistInsertPopup();
+      app.closeAllowlistDeletePopup();
+
+      iziToast.success({
+        color: "#3FBF61",
+        message: data.message,
```
Comment (mlevit) [inline web/src/js/index.js:208]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        message: data.message,
```

File: web/src/js/index.js [hunk 21]
```diff
@@ -1,473 +1,479 @@
...
+            { orderable: false, targets: [0, 1, 2, 3, 4, 5, 6, 7] },
+            {
+              targets: [6],
+              visible: false,
+              searchable: false,
+            },
+          ],
+          dom: "rtp",
+          order: [[6, "desc"]],
+          pageLength: 20,
```
Comment (mlevit) [inline web/src/js/index.js:410]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
          pageLength: 20,
```

File: web/src/js/index.js [hunk 22]
```diff
@@ -1,473 +1,479 @@
...
+}
+
+function init() {
+  getAllowlist();
+  getExecutionLogList();
+  getServices();
+}
+
+// Get the API Gateway Base URL from manifest file
+fetch("serverless.manifest.json").then(function (response) {
```
Comment (mlevit) [inline web/src/js/index.js:458]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
fetch("serverless.manifest.json").then(function (response) {
```

File: web/src/js/index.js [hunk 23]
```diff
@@ -1,473 +1,479 @@
...
+      "x-api-key": API_KEY,
+    },
+  })
+    .then((response) => response.json())
+    .then((data) => {
+      app.executionLogList = data["response"]["logs"].map((row) => {
+        let logDate = new Date(row["date"] + " UTC");
+        let localDate = logDate.toString().split(/ GMT/)[0];
+
+        row["key_escape"] = encodeURIComponent(row["key"]);
```
Comment (mlevit) [inline web/src/js/index.js:296]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        row["key_escape"] = encodeURIComponent(row["key"]);
```

File: web/src/js/index.js [hunk 24]
```diff
@@ -1,473 +1,479 @@
...
+
+        item["expiration_readable"] = readableDate.format(
+          "ddd MMM DD HH:mm:ss YYYY"
+        );
+
+        return item;
+      });
+
+      setTimeout(function () {
+        app.allowlistDataTables = $("#allowlist").DataTable({
```
Comment (mlevit) [inline web/src/js/index.js:398]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
        app.allowlistDataTables = $("#allowlist").DataTable({
```

File: web/src/js/index.js [hunk 25]
```diff
@@ -1,473 +1,479 @@
...
+    },
+    // Execution Log
+    closeExecutionLogPopup: function () {
+      $("html").removeClass("remove-overflow");
+
+      this.executionLogDataTables.destroy();
+
+      this.executionLogActionStats = {};
+      this.executionLogRegionStats = {};
+      this.executionLogServiceStats = {};
```
Comment (mlevit) [inline web/src/js/index.js:151]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792602)
```suggestion
      this.executionLogServiceStats = {};
```
