### PR TITLE
Large execution log support

### LINKED ISSUE #117: Allowlist Elastic Beanstalk resources
A per https://news.ycombinator.com/item?id=31927584#31956513

### LINKED ISSUE #121: Web - Resources Scheduled for Termination View hanging with large csv
Hello thanks for the work on this project, it's great!

Currently I'm running into an issue when viewing the webpage when we have a large number of items on the termination list (~20k+).  

What happens is that when you click on the box to view the resources, it will pull up the modal and start spinning as usual.  It will then hang and not finish.  It seems to fire off the lambda function and that runs successfully, however it is never presented on the webpage.  If you wait a while, occasionally I've gotten a error:
```
Aw, Snap!

Something went wrong while displaying this webpage.

Error code: Out of Memory
```

or in the chrome console:

`index.js:198          GET https://amend.. 2022%2F07%2Faws_resources_scheduled_for_termination_2022_07_07_17_30_04.csv net::ERR_FAILED 504`

We run this on multiple accounts, and most of the accounts are fine; however we have a few accounts with excessive amount of log groups that get populated (the csv file has over 18k listed for one, up to 69k).  

At first I thought it was some of the lambdas memory, increasing them didn't help.  Also tried increasing the ecs task, and didn't seem to help as well.  Currently our workaround has been to disable the specific service with all of the resources (log groups) for the affected accounts.

Not sure yet if this is a limitation on the s3 website or elsewhere.  Currently looking into it and inquiring with AWS as well for the s3 website limitations.

Thanks and take care!

image

### PR DESCRIPTION
**Pull request by mlevit**
## Description

- Added support for very large (20K+) execution log files.
- Added better resource ID placeholders giving users a better indication of expected value.
- Deprecated option to allowlist resources from execution log.

### Related issue(s) (if applicable)

- Fixes #121
- Fixed #117

### CODE REVIEW

File: web/src/js/index.js [hunk 1]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
+            .clear()
+            .rows.add(app.executionLogTable)
+            .draw();
+        }
+        app.showExecutionLogLoadingGif = false;
+        $("#execution-log-table-info").html($("#execution-log-table_info"));
+        $("#execution-log-table-paginate").html(
+          $("#execution-log-table_paginate")
+        );
+      }, 10);
```
Comment (mlevit) [inline web/src/js/index.js:286]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
      }, 10);
```

File: web/src/js/index.js [hunk 2]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
+              },
+            ],
+          });
+        } else {
+          app.executionLogDataTables
+            .clear()
+            .rows.add(app.executionLogTable)
+            .draw();
+        }
+        app.showExecutionLogLoadingGif = false;
```
Comment (mlevit) [inline web/src/js/index.js:281]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
        app.showExecutionLogLoadingGif = false;
```

File: web/src/js/index.js [hunk 3]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
-
-        // region
-        app.executionLogRegionStats[log["1"]] =
-          ++app.executionLogRegionStats[log["1"]] || 1;
-      }
+      setTimeout(function () {
+        if (!app.executionLogDataTables) {
+          app.executionLogDataTables = $("#execution-log-table").DataTable({
+            data: app.executionLogTable,
+            autoWidth: true,
```
Comment (mlevit) [inline web/src/js/index.js:264]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
          autoWidth: true,
```

File: web/src/js/index.js [hunk 4]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
+            deferRender: true,
+            pageLength: 500,
+            dom: "rtip",
+            columnDefs: [
+              {
+                targets: 5,
+                className: "dt-body-nowrap",
+              },
+            ],
```
Comment (mlevit) [inline web/src/js/index.js:273]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
          ],
```

File: web/src/js/index.js [hunk 5]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
-      if (data["response"]["body"][0][7] == "True") {
-        app.executionLogMode = "Dry Run";
-      } else {
-        app.executionLogMode = "Destroy";
+      if (data["response"]["is_compressed"]) {
+        try {
+          let compressedData = Uint8Array.from(
+            atob(app.executionLogTable),
+            (c) => c.charCodeAt(0)
+          );
```
Comment (mlevit) [inline web/src/js/index.js:246]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
        );
```

File: web/src/js/index.js [hunk 6]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
-      }
+      setTimeout(function () {
+        if (!app.executionLogDataTables) {
+          app.executionLogDataTables = $("#execution-log-table").DataTable({
+            data: app.executionLogTable,
+            autoWidth: true,
+            deferRender: true,
+            pageLength: 500,
+            dom: "rtip",
+            columnDefs: [
```
Comment (mlevit) [inline web/src/js/index.js:268]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
          columnDefs: [
```

File: web/src/js/index.js [hunk 7]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
   })
     .then((response) => response.json())
     .then((data) => {
-      app.executionLogTable = data["response"]["body"];
       app.executionLogKey = decodeURIComponent(executionLogUrl);
+      app.executionLogTable = data["response"]["body"];
```
Comment (mlevit) [inline web/src/js/index.js:239]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
      app.executionLogTable = data["response"]["body"];
```

File: web/src/js/index.js [hunk 8]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
+      setTimeout(function () {
+        if (!app.executionLogDataTables) {
+          app.executionLogDataTables = $("#execution-log-table").DataTable({
+            data: app.executionLogTable,
+            autoWidth: true,
+            deferRender: true,
+            pageLength: 500,
+            dom: "rtip",
+            columnDefs: [
+              {
```
Comment (mlevit) [inline web/src/js/index.js:269]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
            {
```

File: web/src/js/index.js [hunk 9]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
 
-        // service and resource
-        app.executionLogServiceStats[log["2"] + " " + log["3"]] =
-          ++app.executionLogServiceStats[log["2"] + " " + log["3"]] || 1;
-
-        // region
-        app.executionLogRegionStats[log["1"]] =
-          ++app.executionLogRegionStats[log["1"]] || 1;
-      }
+      setTimeout(function () {
```
Comment (mlevit) [inline web/src/js/index.js:260]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
      setTimeout(function () {
```

File: web/src/js/index.js [hunk 10]
```diff
@@ -231,43 +235,55 @@ function getExecutionLog(executionLogUrl) {
...
+        if (!app.executionLogDataTables) {
+          app.executionLogDataTables = $("#execution-log-table").DataTable({
```
Comment (mlevit) [inline web/src/js/index.js:262]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
        app.executionLogDataTables = $("#execution-log-table").DataTable({
```

File: web/src/js/index.js (hunk 1 above)
Comment (mlevit) [inline web/src/js/index.js:286]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
      }, 10);
```

File: web/src/js/index.js (hunk 2 above)
Comment (mlevit) [inline web/src/js/index.js:281]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
        app.showExecutionLogLoadingGif = false;
```

File: web/src/js/index.js (hunk 3 above)
Comment (mlevit) [inline web/src/js/index.js:264]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
          autoWidth: true,
```

File: web/src/js/index.js (hunk 4 above)
Comment (mlevit) [inline web/src/js/index.js:273]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
          ],
```

File: web/src/js/index.js (hunk 5 above)
Comment (mlevit) [inline web/src/js/index.js:246]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
        );
```

File: web/src/js/index.js (hunk 6 above)
Comment (mlevit) [inline web/src/js/index.js:268]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
          columnDefs: [
```

File: web/src/js/index.js (hunk 7 above)
Comment (mlevit) [inline web/src/js/index.js:239]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
      app.executionLogTable = data["response"]["body"];
```

File: web/src/js/index.js (hunk 8 above)
Comment (mlevit) [inline web/src/js/index.js:269]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
            {
```

File: web/src/js/index.js (hunk 9 above)
Comment (mlevit) [inline web/src/js/index.js:260]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
      setTimeout(function () {
```

File: web/src/js/index.js (hunk 10 above)
Comment (mlevit) [inline web/src/js/index.js:262]: Codacy has a fix for the issue: [Delete `␍`](https://app.codacy.com/gh/servian/aws-auto-cleanup/pullRequest?prid=9792603)
```suggestion
        app.executionLogDataTables = $("#execution-log-table").DataTable({
```
